[package]
name = "week4-first-program"
version = "0.1.0"
edition = "2021"
description = "Неделя 4: первая Solana Program"

[lib]
crate-type = ["cdylib", "lib"]
name = "week4_first_program"

[features]
default = []
no-entrypoint = []

[dependencies]
borsh = { version = "1.5", features = ["derive"] }
solana-program = "~1.18"
